Fix Python 3.7 GenericMeta not found issue.
abatilo/sanic-swagger pull request #7
Opened 2018-09-13 20:52 UTC by hairychris

2018-09-13 22:36 UTC, abatilo commented
Wow, thanks @hairychris for opening a PR. Could you squash your commits?

2018-09-13 22:42 UTC, hairychris commented
Done, I believe in project settings on Github you can turn on a 'Squash and merge' button if it makes it easier in the future.

2018-09-13 22:42 UTC, hairychris commented
Would you please consider turning issues on? There are some things I've spotted that I don't know whether are bugs or not.

2018-09-14 00:34 UTC, abatilo commented
I didn't even realize that issues were off. And yeah, I don't want to squash everything, but the fluff commits should be squashed. I'm not sure though, why the other build checks aren't running.

2018-09-14 00:35 UTC, hairychris commented
They passed before the squash.

2018-09-14 00:39 UTC, abatilo commented
I've enabled issues. Please feel free to add as many as you can find. I just forked this project and have spent all the time so far, working on tooling to get this project up and running as a serious project.

Lastly, I just changed the CircleCI settings. Could you try pushing an empty commit, or just re-wording your commit message or something like that?

2018-09-14 00:44 UTC, hairychris commented
Tooling looks good, using this library in a project so will try and be helpful where possible. Thanks for tidying these projects up a bit and getting development all into one place.

2018-09-14 00:48 UTC, abatilo commented
Okay, I had two conflicting settings selected (and they didn't have a problem with me clicking save). One last commit please?

Thank you so much for your patience and all of your help.

2018-09-14 00:49 UTC, hairychris commented
No worries, more than happy to get involved, perhaps the first issue should be a roadmap.

> On 14 Sep 2018, at 01:48, Aaron <notifications@github.com> wrote:
> 
> Okay, I had two conflicting settings selected (and they didn't have a problem with me clicking save). One last commit please?
> 
> Thank you so much for your patience and all of your help.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/abatilo/sanic-swagger/pull/7#issuecomment-421195939>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AGSzrfhkbWdxWPd2StV34ROtkLgpFI1gks5uavzxgaJpZM4WoMFy>.
>

2018-09-14 01:09 UTC, abatilo requested changes
Please remove the `.` from the end of your commit subject. And a body for the commit is required as well.

2018-09-14 01:09 UTC, abatilo commented on sanic_swagger/serializer.py
> +import sys
We'll need to move this to the top of the file to comply with PEP8 import order

2018-09-14 01:09 UTC, abatilo commented on sanic_swagger/serializer.py
> +    from typing import GenericMeta
You'll need to add ` # noqa` to the end of this file, so that the linter doesn't complain about this import being not at the top of the file.

2018-09-14 01:24 UTC, abatilo commented on sanic_swagger/serializer.py
>  import attr
We'll need to move this import, and the two below it, to be above the version check.

2018-09-14 01:25 UTC, abatilo commented
If you rebase your branch from master, I merged a change that will fix the issue with the `test` step.

2018-09-14 01:28 UTC, hairychris commented
We should probably document all this in a CONTRIBUTING.md file

2018-09-14 01:29 UTC, abatilo commented
Yeah. I made an issue to add how to run these things locally.

2018-09-14 01:29 UTC, abatilo commented
At least I know that the tooling is all working :|

2018-09-14 02:06 UTC, merged

2018-09-14 02:08 UTC, hairychris commented
Thanks, got tooling and editor setup properly here so everything should be smoother now.